const mongoose = require('mongoose')
const Event = require('./models/Event')
const Spot = require('./models/Spot')
require('dotenv').config()

const addDays = (d, n) => { const r = new Date(d); r.setDate(r.getDate() + n); return r }
const today = new Date()
today.setHours(0, 0, 0, 0)

const seedEvents = async () => {
  await mongoose.connect(process.env.MONGO_URI)

  const spots = await Spot.find()
  const spotByName = {}
  spots.forEach(s => { spotByName[s.name] = s })

  await Event.deleteMany()

  const events = [
    // === LAGOS — linked events ===
    {
      name: 'Saro the Musical',
      city: 'Lagos',
      coordinates: { lat: 6.4489, lng: 3.4369 },
      linkedSpotId: spotByName['Terra Kulture']?._id || null,
      date: addDays(today, 2),
      time: '7:00 PM',
      type: 'Theatre',
      pillar: 'CULTURE',
      tags: ['#PerformingArts', '#Theatre', '#SoftLife', '#PremiumDining'],
      vibe: 'Premium',
      description: 'The award-winning Nigerian Broadway musical returns for a limited run. A vibrant story of culture, ambition, and the Lagos spirit.',
      tip: 'Arrive 30 minutes early to browse the craft shop.',
      status: 'approved',
      isGhostLocation: false,
    },
    {
      name: 'Sip & Paint Sunset Edition',
      city: 'Lagos',
      coordinates: { lat: 6.4281, lng: 3.4219 },
      linkedSpotId: spotByName['Sip and Paint NG']?._id || null,
      date: addDays(today, 1),
      time: '5:00 PM',
      type: 'Creative Social',
      pillar: 'SOCIAL',
      tags: ['#SocialCreative', '#SipAndPaint', '#SoftLife'],
      vibe: 'Chic',
      description: 'An evening of wine, canvases, and Lagos\'s most creative crowd. All materials provided.',
      tip: 'Wear something you don\'t mind getting paint on.',
      status: 'approved',
      isGhostLocation: false,
    },
    {
      name: 'Wellness Sunday at The Truth Beach Club',
      city: 'Lagos',
      coordinates: { lat: 6.4181, lng: 3.4346 },
      linkedSpotId: spotByName['The Truth Beach Club']?._id || null,
      date: addDays(today, 3),
      time: '7:00 AM',
      type: 'Wellness Retreat',
      pillar: 'WELLNESS',
      tags: ['#ActiveWellness', '#Wellness', '#SoftLife', '#SelfCare'],
      vibe: 'Serene',
      description: 'Start your Sunday with beach yoga, guided meditation, and a healthy brunch by the shore.',
      tip: 'Bring a mat and arrive by 6:45 AM for front-row spots.',
      status: 'approved',
      isGhostLocation: false,
    },
    // === LAGOS — ghost location (pop-up) ===
    {
      name: 'The Grape Escape',
      city: 'Lagos',
      coordinates: { lat: 6.4531, lng: 3.4219 },
      linkedSpotId: null,
      date: addDays(today, 7),
      time: '4:00 PM',
      type: 'Wine Festival',
      pillar: 'SOCIAL',
      tags: ['#PremiumDining', '#SoftLife', '#PopUp', '#Wine', '#LuxuryLifestyle'],
      vibe: 'Premium',
      description: 'A curated wine-tasting experience featuring exclusive vineyards, gourmet pairings, and live jazz at a secret Ikoyi location.',
      tip: 'Location revealed 24 hours before to ticket holders.',
      status: 'approved',
      isGhostLocation: true,
    },
    // === LAGOS — draft (pending review) ===
    {
      name: 'Afro-Jazz Night at The Shrine',
      city: 'Lagos',
      coordinates: { lat: 6.4731, lng: 3.4774 },
      linkedSpotId: spotByName['New Afrika Shrine']?._id || null,
      date: addDays(today, 14),
      time: '8:00 PM',
      type: 'Live Music',
      pillar: 'CULTURE',
      tags: ['#PerformingArts', '#Afrobeat', '#SocialCreative'],
      vibe: 'Vibrant',
      description: 'A special Afro-jazz fusion night featuring guest artists from across West Africa.',
      tip: 'Street parking fills up fast — use ride-sharing.',
      status: 'draft',
      isGhostLocation: false,
    },
    // === LAGOS — past event (archived) ===
    {
      name: 'Lagos Art Week Opening',
      city: 'Lagos',
      coordinates: { lat: 6.4431, lng: 3.4377 },
      linkedSpotId: spotByName['Nike Art Gallery']?._id || null,
      date: addDays(today, -10),
      time: '10:00 AM',
      type: 'Art Exhibition',
      pillar: 'CULTURE',
      tags: ['#QuietIntellectual', '#Art', '#Exhibition'],
      vibe: 'Curated',
      description: 'The opening of Lagos Art Week featuring emerging Nigerian contemporary artists.',
      tip: '',
      status: 'archived',
      isGhostLocation: false,
    },
    // === NAIROBI — linked events ===
    {
      name: 'Blankets & Wine: Summer Edition',
      city: 'Nairobi',
      coordinates: { lat: -1.3432, lng: 36.7466 },
      linkedSpotId: spotByName['Blankets & Wine Nairobi']?._id || null,
      date: addDays(today, 5),
      time: '2:00 PM',
      type: 'Live Music & Picnic',
      pillar: 'SOCIAL',
      tags: ['#SocialCreative', '#PerformingArts', '#ThePlot', '#Sundowner'],
      vibe: 'Chic',
      description: 'Kenya\'s premier picnic concert series. Curated lineup, gourmet food stalls, and a sunset that steals the show.',
      tip: 'Bring a blanket and arrive early for the best spot on the lawn.',
      status: 'approved',
      isGhostLocation: false,
    },
    {
      name: 'Sundowners at Karura',
      city: 'Nairobi',
      coordinates: { lat: -1.2333, lng: 36.8333 },
      linkedSpotId: spotByName['Karura Forest']?._id || null,
      date: addDays(today, 4),
      time: '5:30 PM',
      type: 'Nature Social',
      pillar: 'WELLNESS',
      tags: ['#ActiveWellness', '#Sundowner', '#ThePlot', '#NatureWalk'],
      vibe: 'Serene',
      description: 'An evening guided forest walk ending with drinks and canapés at the Karura waterfalls.',
      tip: 'Wear comfortable sneakers and bring insect repellent.',
      status: 'approved',
      isGhostLocation: false,
    },
    // === NAIROBI — ghost location ===
    {
      name: 'The Secret Rooftop Jazz Session',
      city: 'Nairobi',
      coordinates: { lat: -1.2864, lng: 36.8172 },
      linkedSpotId: null,
      date: addDays(today, 6),
      time: '7:00 PM',
      type: 'Live Music',
      pillar: 'CULTURE',
      tags: ['#PerformingArts', '#Jazz', '#PopUp', '#SecretLocation', '#IntimateMusic'],
      vibe: 'Intimate',
      description: 'An undisclosed rooftop in Westlands hosts an evening of soulful jazz, craft cocktails, and Nairobi\'s creative class.',
      tip: 'Address sent via email on the day. Dress sharp.',
      status: 'approved',
      isGhostLocation: true,
    },
    // === NAIROBI — draft ===
    {
      name: 'Pottery & Pinot Workshop',
      city: 'Nairobi',
      coordinates: { lat: -1.2611, lng: 36.8046 },
      linkedSpotId: null,
      date: addDays(today, 21),
      time: '3:00 PM',
      type: 'Workshop',
      pillar: 'CULTURE',
      tags: ['#Pottery', '#Artisan', '#SipAndPaint', '#SocialCreative'],
      vibe: 'Curated',
      description: 'A hands-on pottery class paired with South African wines. Take home your own handmade ceramic piece.',
      tip: 'Aprons provided but wear clothes you don\'t mind getting messy.',
      status: 'draft',
      isGhostLocation: true,
    },
    // === KIGALI ===
    {
      name: 'Inema Arts Open Studio Evening',
      city: 'Kigali',
      coordinates: { lat: -1.9474, lng: 30.0648 },
      linkedSpotId: spotByName['Inema Arts Center']?._id || null,
      date: addDays(today, 2),
      time: '6:00 PM',
      type: 'Art Social',
      pillar: 'CULTURE',
      tags: ['#SocialCreative', '#Art', '#Sherehe', '#Intimate'],
      vibe: 'Intimate',
      description: 'Meet the artists behind Rwanda\'s most dynamic art studio. Live drumming, canapés, and exclusive previews of new collections.',
      tip: 'Saturday visits include live drumming performances.',
      status: 'approved',
      isGhostLocation: false,
    },
    {
      name: 'Cuvée & Cuisine: Wine Dinner',
      city: 'Kigali',
      coordinates: { lat: -1.9536, lng: 30.0709 },
      linkedSpotId: null,
      date: addDays(today, 9),
      time: '7:00 PM',
      type: 'Gastronomy',
      pillar: 'SOCIAL',
      tags: ['#PremiumDining', '#Wine', '#Cuvée', '#Gastronomy'],
      vibe: 'Premium',
      description: 'A five-course tasting menu paired with rare South African and French wines at an intimate Kacyiri villa.',
      tip: 'Dietary requirements must be submitted 48 hours in advance.',
      status: 'approved',
      isGhostLocation: true,
    },
    {
      name: 'Ophil Wellness: Full Moon Reset',
      city: 'Abuja',
      coordinates: { lat: 9.0417, lng: 7.4919 },
      linkedSpotId: spotByName['Ophil Wellness']?._id || null,
      date: addDays(today, 8),
      time: '6:00 PM',
      type: 'Wellness Evening',
      pillar: 'WELLNESS',
      tags: ['#ActiveWellness', '#Wellness', '#SelfCare', '#Intimate'],
      vibe: 'Serene',
      description: 'An intimate full moon wellness session with guided meditation, sound healing, and herbal teas by the lake.',
      tip: 'Follow their Instagram for last-minute location updates.',
      status: 'approved',
      isGhostLocation: false,
    },
    // === "Today" events — for Live Tonight badge testing ===
    {
      name: 'Jazz at The Jazz Lounge',
      city: 'Abuja',
      coordinates: { lat: 9.0581, lng: 7.4897 },
      linkedSpotId: spotByName['The Jazz Lounge Abuja']?._id || null,
      date: today,
      time: '8:00 PM',
      type: 'Live Music',
      pillar: 'SOCIAL',
      tags: ['#PerformingArts', '#Jazz', '#IntimateMusic', '#SoftLife'],
      vibe: 'Intimate',
      description: 'Tonight only: a special acoustic set featuring West Africa\'s finest jazz ensemble.',
      tip: 'Reserve a table for weekend shows.',
      status: 'approved',
      isGhostLocation: false,
    },
  {
    name: 'Sunset Yoga at Jabi Lake',
    city: 'Abuja',
    coordinates: { lat: 9.0648, lng: 7.4716 },
    linkedSpotId: spotByName['Reset Club Social']?._id || null,
    date: today,
    time: '5:30 PM',
    type: 'Wellness',
    pillar: 'WELLNESS',
    tags: ['#ActiveWellness', '#Wellness', '#SelfCare'],
    vibe: 'Serene',
    description: 'End your day with guided sunset yoga by the lake, followed by herbal teas and cold-pressed juices.',
    tip: 'Bring your own mat and a light jacket for after sunset.',
    status: 'approved',
    isGhostLocation: false,
  },
  // === FESTIVALS & SPECIAL EVENTS (from spec) ===
  {
    name: 'Lagos Gallery Weekend',
    city: 'Lagos',
    coordinates: { lat: 6.4431, lng: 3.4377 },
    linkedSpotId: null,
    date: new Date(2026, 2, 14),
    endDate: new Date(2026, 2, 16),
    time: '10:00 AM',
    type: 'Art Exhibition',
    pillar: 'CULTURE',
    tags: ['#PerformingArts', '#SocialCreative', '#Art'],
    vibe: 'Curated',
    description: 'An annual city-wide art festival featuring curated gallery tours, private openings, and exclusive meet-the-artist sessions across Lagos.',
    tip: "Wear comfortable walking shoes — you'll be gallery-hopping across the city.",
    status: 'approved',
    isGhostLocation: true,
  },
  {
    name: 'Fanti Carnival',
    city: 'Lagos',
    coordinates: { lat: 6.4531, lng: 3.4019 },
    linkedSpotId: null,
    date: addDays(today, 30),
    time: '12:00 PM',
    type: 'Festival',
    pillar: 'CULTURE',
    tags: ['#PerformingArts', '#SocialCreative', '#Festival'],
    vibe: 'Vibrant',
    description: 'A vibrant Easter tradition celebrating Afro-Brazilian heritage with samba-style parades, masquerades, and street parties on Lagos Island.',
    tip: 'Join the parade — costumes are part of the experience.',
    status: 'approved',
    isGhostLocation: true,
  },
  {
    name: 'Lagos Igbo Hangout',
    city: 'Lagos',
    coordinates: { lat: 6.4731, lng: 3.4774 },
    linkedSpotId: null,
    date: new Date(2026, 5, 21),
    endDate: new Date(2026, 5, 22),
    time: '10:00 AM',
    type: 'Festival',
    pillar: 'CULTURE',
    tags: ['#SocialCreative', '#Festival'],
    vibe: 'Vibrant',
    description: 'An annual heritage celebration at FHA Field, Festac. Showcasing Igbo culture through music, dance, food, and traditional ceremonies.',
    tip: 'Try the Ofe Oha and pounded yam — it\'s the festival\'s signature dish.',
    status: 'approved',
    isGhostLocation: true,
  },
  {
    name: 'NIBF Book Fair',
    city: 'Lagos',
    coordinates: { lat: 6.4431, lng: 3.4377 },
    linkedSpotId: null,
    date: new Date(2026, 4, 13),
    time: '9:00 AM',
    type: 'Book Fair',
    pillar: 'CULTURE',
    tags: ['#QuietIntellectual', '#SocialCreative'],
    vibe: 'Curated',
    description: 'The Nigerian International Book Fair at Wole Soyinka Centre. A major publishing convention with authors, publishers, and literary discussions.',
    tip: 'Arrive early for author signing sessions — queues form quickly.',
    status: 'approved',
    isGhostLocation: true,
  },
  {
    name: 'Vibes with Friends',
    city: 'Lagos',
    coordinates: { lat: 6.4689, lng: 3.4093 },
    linkedSpotId: null,
    date: new Date(2026, 4, 16),
    time: '4:00 PM',
    type: 'Live Music',
    pillar: 'SOCIAL',
    tags: ['#SocialCreative', '#PerformingArts'],
    vibe: 'Vibrant',
    description: 'Reekado Banks and Ajebo at Ikorodu Ferry. An afternoon of live Afrobeat and networking with Lagos creative community.',
    tip: 'Ferry parking is limited — use ride-sharing or carpool.',
    status: 'approved',
    isGhostLocation: true,
  },
  {
    name: 'The Link Up Abuja',
    city: 'Abuja',
    coordinates: { lat: 9.0579, lng: 7.4905 },
    linkedSpotId: null,
    date: new Date(2026, 4, 16),
    time: '6:00 PM',
    type: 'Networking Social',
    pillar: 'SOCIAL',
    tags: ['#SocialCreative'],
    vibe: 'Premium',
    description: 'A premium networking and social mixer at Continental Hotel. Connect with Abuja\'s creative and professional class.',
    tip: 'Bring business cards — the networking here is serious.',
    status: 'approved',
    isGhostLocation: true,
  },
  {
    name: 'Bole Afri Fest Weekend',
    city: 'Abuja',
    coordinates: { lat: 9.0579, lng: 7.4905 },
    linkedSpotId: spotByName['Bole Afri Fest']?._id || null,
    date: new Date(2026, 4, 30),
    endDate: new Date(2026, 5, 1),
    time: '12:00 PM',
    type: 'Festival',
    pillar: 'CULTURE',
    tags: ['#SocialCreative', '#Festival', '#Owambe'],
    vibe: 'Vibrant',
    description: 'Nigeria\'s biggest barbecue and culture festival at Gongola Park. Live music, cooking competitions, and the best bole in Abuja.',
    tip: 'Expect high crowds at Gongola Park — arrive by 2 PM for the best food selections.',
    status: 'approved',
    isGhostLocation: false,
  },
  {
    name: 'Ellipopi\'s Tour',
    city: 'Lagos',
    coordinates: { lat: 6.4489, lng: 3.4369 },
    linkedSpotId: null,
    date: new Date(2026, 8, 19),
    time: '7:00 PM',
    type: 'Live Music',
    pillar: 'SOCIAL',
    tags: ['#PerformingArts', '#SocialCreative'],
    vibe: 'Chic',
    description: 'Ellipopi brings Afro-fusion to Livespot Center for an unforgettable night of genre-blending music and performance.',
    tip: 'Tickets sell out fast — book at least two weeks in advance.',
    status: 'approved',
    isGhostLocation: true,
  },
  {
    name: 'Nuvolition Fashion Show',
    city: 'Lagos',
    coordinates: { lat: 6.4281, lng: 3.4219 },
    linkedSpotId: null,
    date: new Date(2026, 8, 24),
    time: '3:00 PM',
    type: 'Fashion Show',
    pillar: 'SOCIAL',
    tags: ['#SocialCreative', '#PerformingArts'],
    vibe: 'Premium',
    description: 'An African creativity showcase at Muri Okunola Park featuring emerging designers, bold collections, and live performances.',
    tip: 'Street style is part of the show — dress to impress.',
    status: 'approved',
    isGhostLocation: true,
  },
  {
    name: 'Africa Fashion Week Abuja',
    city: 'Abuja',
    coordinates: { lat: 9.0579, lng: 7.4905 },
    linkedSpotId: spotByName['Africa Fashion Week Abuja']?._id || null,
    date: new Date(2026, 10, 27),
    time: '10:00 AM',
    type: 'Fashion Week',
    pillar: 'CULTURE',
    tags: ['#SocialCreative'],
    vibe: 'Premium',
    description: 'A showcase of top African designers with runway shows, pop-up markets, and networking events at Continental Hotel.',
    tip: 'Book tickets early — this event sells out months in advance.',
    status: 'approved',
    isGhostLocation: false,
  },
  {
    name: 'King James 20th Anniversary',
    city: 'Kigali',
    coordinates: { lat: -1.9527, lng: 30.0913 },
    linkedSpotId: null,
    date: new Date(2026, 7, 1),
    time: '7:00 PM',
    type: 'Concert',
    pillar: 'SOCIAL',
    tags: ['#PerformingArts', '#SocialCreative'],
    vibe: 'Vibrant',
    description: 'A major musical milestone — King James celebrates 20 years at BK Arena with guest artists from across East Africa.',
    tip: 'BK Arena gets crowded — use the public parking and arrive by 6 PM.',
    status: 'approved',
    isGhostLocation: true,
  },
  {
    name: 'Blankets & Wine Summer Edition',
    city: 'Nairobi',
    coordinates: { lat: -1.3432, lng: 36.7466 },
    linkedSpotId: spotByName['Blankets & Wine Nairobi']?._id || null,
    date: new Date(2026, 5, 7),
    time: '2:00 PM',
    type: 'Live Music & Picnic',
    pillar: 'SOCIAL',
    tags: ['#SocialCreative', '#PerformingArts', '#Sundowner'],
    vibe: 'Chic',
    description: 'The iconic outdoor picnic concert at Kasarani. Curated lineup of Kenya\'s finest musicians, gourmet food, and sunset vibes.',
    tip: 'Bring a blanket and arrive early for the best spot on the lawn.',
    status: 'approved',
    isGhostLocation: false,
  },
  {
    name: 'Kenya Food Festival',
    city: 'Nairobi',
    coordinates: { lat: -1.3456, lng: 36.7567 },
    linkedSpotId: spotByName['Kenya Food Festival']?._id || null,
    date: new Date(2026, 7, 14),
    time: '10:00 AM',
    type: 'Food Festival',
    pillar: 'SOCIAL',
    tags: ['#SocialCreative'],
    vibe: 'Vibrant',
    description: 'All 47 Kenyan counties represented at Uhuru Gardens. A massive celebration of Kenyan cuisine, culture, and agricultural diversity.',
    tip: 'Come hungry and pace yourself — 47 counties means 47 different dishes to try.',
    status: 'approved',
    isGhostLocation: false,
  },
  {
    name: 'Pan-African Biennale Opening',
    city: 'Nairobi',
    coordinates: { lat: -1.2895, lng: 36.8219 },
    linkedSpotId: null,
    date: new Date(2026, 8, 7),
    time: '10:00 AM',
    type: 'Art & Design Expo',
    pillar: 'CULTURE',
    tags: ['#PerformingArts', '#QuietIntellectual'],
    vibe: 'Curated',
    description: 'A major Pan-African architecture and design exhibition at KICC showcasing the best of African creative innovation.',
    tip: 'Allocate at least 3 hours — the exhibits are extensive.',
    status: 'approved',
    isGhostLocation: true,
  },
  {
    name: 'Private Jams: Jazz Evening',
    city: 'Lagos',
    coordinates: { lat: 6.4489, lng: 3.4369 },
    linkedSpotId: null,
    date: addDays(today, 14),
    time: '8:00 PM',
    type: 'Live Music',
    pillar: 'CULTURE',
    tags: ['#PerformingArts', '#QuietIntellectual'],
    vibe: 'Intimate',
    description: 'An exclusive private listening session featuring curated jazz and Afro-soul at a boutique hotel in Lagos. Intimate, sophisticated, and deeply cultural.',
    tip: 'These sessions are intentionally small — book as soon as you see availability.',
    status: 'approved',
    isGhostLocation: true,
  },
]

  await Event.insertMany(events)
  const count = await Event.countDocuments()
  console.log(`Seeded ${events.length} events (total: ${count})`)
  mongoose.connection.close()
}

seedEvents()
